wandb_version: 1

batch_size:
  value: 16
embeddings_size:
  value: 50
epochs:
  value: 5
hidden_units:
  value: 64
lr:
  value: 0.0001
ngram:
  value: 4
test_pct:
  value: 0.1
text_type:
  value: word
