_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.8
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: 128
embeddings_size:
    value: 50
epochs:
    value: 5
hidden_units:
    value: 512
lr:
    value: 0.001
ngram:
    value: 2
test_pct:
    value: 0.1
